### ISSUE TITLE
"[rviz-2] process has died" when confirm "roslaunch polygon_coverage_ros coverage_planner.launch "

### ISSUE THREAD

**Issue by Joy-Zhang-0303** [ethz-asl/polygon_coverage_planning#36]
Hello, polygon_coverage_planning development team, 

When I use this package to confirm the coverage_planner, I meet the error as below and I can not confirm the result like the youtube video.
**My environment is:**

- Ubuntu 18.04 x86_64

- ROS Melodic 

Error:
[rviz-2] process has died [pid 11289, exit code -11, cmd /opt/ros/melodic/lib/rviz/rviz -d /home/shiraishi-lab/Documents/15.RosDevelopmentUse/catkin_ws_coverage_planning/src/polygon_coverage_planning/polygon_coverage_ros/cfg/rviz/coverage_planner.rviz __name:=rviz __log:=/home/shiraishi-lab/.ros/log/0f6838d2-c279-11ea-b58f-4c1d96b56f67/rviz-2.log].
log file: /home/shiraishi-lab/.ros/log/0f6838d2-c279-11ea-b58f-4c1d96b56f67/rviz-2*.log

![Screenshot from 2020-07-10 15-52-09](https://user-images.githubusercontent.com/48177679/87125355-56dea880-c2c5-11ea-95b2-f901b1253751.png)

Could you please give some advices about how to fix this issue.

Thanks and Best Regards.
Gunma University , Japan
Zhang

**Comment by rikba** [comment]
Hi @Joy-Zhang-0303

I tried reproducing the error. I defined the polygon as a yaml file (see https://github.com/ethz-asl/polygon_coverage_planning/pull/38). The planner is started through 
```roslaunch polygon_coverage_ros coverage_planner.launch```
and called the planner through service
```
rosservice call /coverage_planner/plan_path "start_pose:
  header:
    seq: 0
    stamp: {secs: 0, nsecs: 0}
    frame_id: ''
  pose:
    position: {x: 15.8929, y: 90.9999, z: 0.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}
start_velocity: {x: 0.0, y: 0.0, z: 0.0}
goal_pose:
  header:
    seq: 0
    stamp: {secs: 0, nsecs: 0}
    frame_id: ''
  pose:
    position: {x: 86.9455, y: 12.2954, z: 0.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}
goal_velocity: {x: 0.0, y: 0.0, z: 0.0}
bounding_box: {x: 0.0, y: 0.0, z: 0.0}"
```

This is the resulting visualization of the plan I get.
![coverage](https://user-images.githubusercontent.com/11293852/88029992-fceaa800-cb3a-11ea-9b09-b61f15c1d544.png)

It seems to me that for some reason RVIZ is crashing in your case. Try to deactivate the visualization of the path before selecting the goal point. Then successively activate visualization again to find the error source, e.g., move camera away from where path is created.
![Screenshot_2020-07-21_10-17-02](https://user-images.githubusercontent.com/11293852/88030518-a0d45380-cb3b-11ea-8058-2417fc6dc923.png)
